Feature/3,4
horba/IntelliGram-D pull request #20
Opened 2017-11-25 23:07 UTC by vladkvts

Merged tasks #3 and #4 and commited changes from previous pull request

2017-11-26 06:14 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                return Ok(200);
Что значит 200?

2017-11-26 06:16 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                using (SqlConnection connection =
На сколько я понял, лучше var connection

2017-11-26 06:19 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                        bool isConfigExists = reader.HasRows;
То же саамое что и
 if (reader.HasRows)

2017-11-26 06:35 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                        !Convert.ToBoolean(checkUniqueInstagramCmd.ExecuteScalar());
Может тут переименовать переменную? На сколько я понял, она означает отсутствие записи в таблице. Было бы неплохо переименовать в isNewConfig или что-то более понятное.

2017-11-26 11:22 UTC, AkulovBogdan commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                using (SqlConnection connection =
Согласен, не везде пофиксил

2017-11-26 11:23 UTC, AkulovBogdan commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                        bool isConfigExists = reader.HasRows;
Да, но я думаю от одной переменной ничего существенно не поменяется, но код стал немного понятнее

2017-11-26 11:23 UTC, AkulovBogdan commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                        !Convert.ToBoolean(checkUniqueInstagramCmd.ExecuteScalar());
Пожалуй соглашусь

2017-11-28 20:55 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                    return null;
Что делать потом фронту с ответом - null?

2017-11-28 20:55 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                return null;
все тот же вопрос про ответ null

2017-11-28 20:55 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +            return new ConfigurationModel { InstaUsername = "defaultName", InstaPassword = "defaultPass", TelegramUsername = "defaultTelegram", Tags = "def, ault", Topics = "def, ault" };
что делает этот метод? почему так?

2017-11-28 20:55 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                return Ok(200);
const int RESPONSE_STATUS_OK

2017-11-28 20:55 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +        public ConfigurationModel GetConfig(int id)
твой метод несколько "распухший".
Попробуй повыносить код в методы.

2017-11-28 20:56 UTC, AkulovBogdan commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +            return new ConfigurationModel { InstaUsername = "defaultName", InstaPassword = "defaultPass", TelegramUsername = "defaultTelegram", Tags = "def, ault", Topics = "def, ault" };
Выводит дефолтную конфигу

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +        ConfigService configService = new ConfigService();
IConfigService

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
>          public ConfigurationModel Get()
есть ли еще смысл в этом методе?

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                        throw new Exception();
о чем должно сказать это исключение?

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                catch
какой смысл в этом catch?
он и без этого передастся выше по стеку

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                    catch
какой смысл в этом catch?
он и так передастся выше по стеку, если ты не собираешься здесь его обрабатывать

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +            return null;
null уместен в возвращаемом значении только в случае если такой конфиг не нашелся

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                if (!TagExists(tag, connection, out int tagId))
считается не очень хорошей практикой, когда метод, который проверяет на существование чего-либо,имеет сайд-эффект в виде изменения некой другой внешней переменной. и вообще не очень хорошо иметь сайд эффекты.
В данном случае  можно попробовать решить твою проблему следующим путем:
завести функцию int? getTagId(string tag) и сравнивать c null в этом месте.

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                if (!TopicExists(topic, connection, out int topicId))
аналогично TagExist

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                foreach (string tag in tags)
мне кажется, подобный кусок кода я уже встречала.
Возможно, получится это вынести в отдельную функцию?

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +            catch
no sence

2017-11-28 21:38 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +        private void AddConfig(ConfigurationModel model, SqlConnection connection)
метод великоват.

2017-11-28 21:46 UTC, vladkvts commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                    return null;
Просто не знал, что вернуть, может тогда дефолтную конфигурацию, если мы её оставим ?

2017-11-28 21:58 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                    return null;
валидационный ексепшн

2017-11-28 21:59 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +            return new ConfigurationModel { InstaUsername = "defaultName", InstaPassword = "defaultPass", TelegramUsername = "defaultTelegram", Tags = "def, ault", Topics = "def, ault" };
под это лучше завести метод getDefaultConfig

2017-12-03 22:53 UTC, horba requested changes
исправь замечания, пожалуйста

2017-12-03 23:52 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +            connectionString = "Server=DESKTOP-2J18FL2\\SQLEXPRESS;Database=Configuration;Trusted_Connection=True;";
почему использовать захардкоженную строку, а не первый закоменнтированный вариант?

2017-12-03 23:52 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                new SqlCommand("INSERT INTO Tag (Tag) VALUES (@Tag);SELECT @TagID = SCOPE_IDENTITY()", connection);
тут две sql команды в одной строке. почему так? это с каким-то умыслом сделано?

2017-12-03 23:52 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Models/ConfigService.cs
> +                "SELECT @TopicID = TopicID FROM Topic WHERE Topic = @Topic", connection);
зачем здесь два select'а в одной команде?

2018-01-08 22:22 UTC, merged