Feature/14
horba/IntelliGram-D pull request #28
Opened 2017-12-04 22:06 UTC by groleore

Add testing implementation for method SendMessage in TelegramService

2017-12-04 23:27 UTC, demosglok reviewed
есть такое понятие - связность.  ее стараются уменьшат. что б разные модули поменьше знали друг о друге. эта конкретная реализация сервиса слишком много знает (смайлик прищуренной уточки). 
она что-то знает про базу и что-то из нее добывает. хотя все что этому сервису нужно  - это только работать с телеграммом. все остальное он должен получать в качестве входных парамеров, сводя тем самым к минимуму внешние зависимости. 

поэтому рекомендую убрать весь код работы с бд и оставить получение необходимых данных для отправки сообщения через параметры (параметры конструктора или метода)

2017-12-04 23:28 UTC, demosglok requested changes
попробуй быстренько это поменять, вроде только удалить чуть-чуть и пару строк добавить

2017-12-04 23:46 UTC, groleore commented
Нормально, если вынести взаимодействие с базой в отдельный сервис UserService, а в этом вызвать необходимый метод?

2017-12-05 00:06 UTC, demosglok commented
TelegramService по идее не должен вообще ничего о базе знать, если только он какие-то свои внутренние данные в базе не хранит.  
лучше через параметры все передавать чем через UserService вытягивать, тк это лишние зависимости (в данном случае от UserService'а)
тогда уж проще готовую модельку передать (ну или просто plain параметры) чем давать id и заставлять один сервис по этому id добывать данные из другого сервиса

2017-12-05 09:03 UTC, demosglok approved these changes

2017-12-05 09:03 UTC, merged