Feature/18
horba/IntelliGram-D pull request #29
Opened 2017-12-05 04:28 UTC by siriak

2017-12-05 09:08 UTC, demosglok requested changes

2017-12-05 09:08 UTC, demosglok commented on InstaBotPrototype/DBMigrator/DBMigration.cs
> +                WriteLine("Error happened");
почему убирать текст ексепшна из сообщения об ошибке?

2017-12-05 09:08 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +            return (int)id;
id.Value?

2017-12-05 09:08 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +            if (id == null)
id.HasValue?

2017-12-05 09:08 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +        public int Register(string login, string password)
мы при регистрации пользователя только два поля добавляем, логи-пароль? какой-нить email не нужно добавить?

2017-12-05 09:08 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +            insert.CommandText = $"insert into table dbo.Users (Login, Password) values ('{login}', '{password}')";
наверное еще было б неплохо для статистики иметь дату регистрации пользователя

2017-12-05 15:52 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +        public int Register(string login, string password)
Пока что нигде не мелькало что нужно емейл

2017-12-05 16:01 UTC, siriak commented on InstaBotPrototype/DBMigrator/DBMigration.cs
> +                WriteLine("Error happened");
Потому что этот эксепшн должен случаться если мы запускаем приложение в первый раз. Тогда отсутствует табличка миграций и проверка на применимость ломается. Это не должно сильно выглядеть как ошибка т.к. это не баг, а фича.

2017-12-05 22:10 UTC, demosglok commented on InstaBotPrototype/DBMigrator/DBMigration.cs
> +                WriteLine("Error happened");
тогда не очень правильно писать слово error в консоль. если это фича

2017-12-05 22:12 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +        public int Register(string login, string password)
да. но очень часто при регистрации дофига все указывается. и емейл - один из самых распространенных вариантов. 
я это все к тому что б использовать тут RegisterModel со всякими полями, а не передавать каждое поле отдельным параметром. ибо когда таких полей станет 10, будет некрасиво

2017-12-09 20:48 UTC, horba commented
порезолви конфликты, пожалуйста

2017-12-11 11:43 UTC, groleore commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +                updateLastLogin.CommandText = $"update dbo.Users LastLogin = SYSDATETIME() where Id = @id";
Стоит подправить синтаксис запроса. Пропущено ключевое слово SET.

2017-12-11 13:18 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +                updateLastLogin.CommandText = $"update dbo.Users LastLogin = SYSDATETIME() where Id = @id";
Готово

2017-12-18 20:55 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AuthenticationService.cs
> +        DbParameter GetParameter(string name, object value)
вот тут обоснованность выделения такого метода мне не очень очевидна. но пусть пока будет. только назови его CreateParameter, а не Get. Get точно не отображает его содержимое - которое создает, а не получает откуда-то параметр

2017-12-19 08:31 UTC, merged