Feature/44
horba/IntelliGram-D pull request #50
Opened 2018-01-05 16:02 UTC by siriak

Гугл распознаватель я не могу сделать т,к, там нужен номер карты чтобы зарегистрироваться, а у меня такой карты нет.

2018-01-13 04:13 UTC, groleore requested changes
Можно расширить абстрактный класс ImageRecognizer

2018-01-13 04:13 UTC, groleore commented on InstaBotPrototype/InstaBotPrototype/Services/AI/ImageRecognizer.cs
> +        public abstract IEnumerable<string> RecognizeTopic(string imageFilePath);
Логика этого метода общая для любого класса-наследника, поэтому его реализацию можно перенести в абстрактный класс (аналогично для RecognizeTopicAsync(string imageFilePath))

2018-01-13 04:13 UTC, groleore commented on InstaBotPrototype/InstaBotPrototype/Services/AI/MicrosoftImageRecognizer.cs
> +        static byte[] GetImageAsByteArray(string imageFilePath)
Можно вынести в абстрактный класс ImageRecognizer как защищенный метод.

2018-01-13 12:34 UTC, siriak commented
Можно снова ревьювить

2018-01-13 18:20 UTC, groleore submitted a review, later dismissed

2018-01-21 20:08 UTC, demosglok requested changes
один коммент по юзингам только

2018-01-21 20:08 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/AI/ImageRecognizer.cs
> +            var fileStream = new FileStream(imageFilePath, FileMode.Open, FileAccess.Read);
тут нигде не надо using использовать? для FileStream вроде надо. для BinaryReader вроде тоже

2018-01-21 20:19 UTC, demosglok approved these changes

2018-01-21 20:20 UTC, merged