Feature/3 слой для работы с БД, feature/4 Интегрировать контроллер и слой бд,feature/24 Tag и Topic model
horba/IntelliGram-D pull request #56
Opened 2018-01-10 22:57 UTC by vladkvts

2018-01-12 17:25 UTC, siriak requested changes

2018-01-12 17:25 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082220_CreateTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.Topic(TopicID int identity(1,1), Topic nvarchar(128) not null, primary key(TopicID))";
Может TopicID и прочие аналогичные переименовать в Id? Как по мне, это просто удобнее. Посмотрел дальше,  думаю уже не стоит менять, слишком затратно, но в будущем Id звучит лучше)

2018-01-12 17:25 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082226_CreateConfigTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTopic(ConfigID int not null, TopicID int not null)";
Это нормально иметь таблицу без ключа? Никогда просто такого не видел. И, на сколько я понимаю, тут необходимы внешние ключи.

2018-01-12 17:25 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082231_CreateConfigTagTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTag(ConfigID int not null, TagID int not null)";
То же самое.

2018-01-12 17:25 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082236_CreateTelegramUsersTable.cs
> +            ApplyCommand.CommandText = "create table dbo.TelegramUsers(ChatID int not null, FirstName nvarchar(128) not null, LastName nvarchar(128) not null, VerificationKey int, UserID int)";
Что из этого ключ?

2018-01-14 19:56 UTC, horba requested changes

2018-01-14 19:56 UTC, horba commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082226_CreateConfigTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTopic(ConfigID int not null, TopicID int not null)";
++

2018-01-14 19:56 UTC, horba commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082236_CreateTelegramUsersTable.cs
> +            ApplyCommand.CommandText = "create table dbo.TelegramUsers(ChatID int not null, FirstName nvarchar(128) not null, LastName nvarchar(128) not null, VerificationKey int, UserID int)";
++

2018-01-14 19:56 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                }
смысл?

2018-01-14 19:56 UTC, horba commented on InstaBotPrototype/InstaBotPrototype/Controllers/ConfigurationController.cs
> +                    throw e;
тоже самое

2018-01-14 21:10 UTC, horba approved these changes

2018-01-14 21:11 UTC, merged