Feature/46
horba/IntelliGram-D pull request #63
Opened 2018-01-26 19:41 UTC by groleore

2018-01-26 20:21 UTC, siriak requested changes

2018-01-26 20:21 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M201801242024_AddUserIdColumnToConfigurationTable.cs
> +            ReverseCommand.CommandText = "drop table dbo.InstagramIntegration";
Может всё таки "ALTER TABLE dbo.Configuration DROP COLUMN UserId"?

2018-01-26 20:21 UTC, siriak commented on InstaBotPrototype/InstagramIntegration/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
Лучше 4.7.1 поставить, а то может ругаться

2018-01-26 20:21 UTC, siriak commented on InstaBotPrototype/InstagramIntegration/Program.cs
> +                    tags.Add(tagsReader.GetString(0));
Скобочки

2018-01-26 20:21 UTC, siriak commented on InstaBotPrototype/InstagramIntegration/Program.cs
> +                    nicknames.Add(nameReader.GetString(0));
Скобочки тут и дальше. У нас в стиле написано что всегда нужно ставить скобки в циклах и в операторах ветвления.

2018-01-27 19:37 UTC, groleore commented
Исправил замечания. Можно еще раз ревьювить.

2018-01-28 07:13 UTC, siriak submitted a review, later dismissed

2018-01-29 23:39 UTC, AkulovBogdan commented on InstaBotPrototype/InstagramIntegration/Program.cs
> +            List<string> topics = new List<string>();
Возможно лучше было бы var

2018-01-29 23:39 UTC, AkulovBogdan commented on InstaBotPrototype/InstagramIntegration/Program.cs
> +            List<string> tags = new List<string>();
Тут тоже

2018-01-29 23:40 UTC, AkulovBogdan commented on InstaBotPrototype/InstagramIntegration/Program.cs
> +            List<string> nicknames = new List<string>();
И тут

2018-01-29 23:43 UTC, AkulovBogdan commented on InstaBotPrototype/InstagramIntegration/Program.cs
> +                Console.WriteLine(String.Format("User : {0}", user));
Может быть тут лучше использовать $""?

2018-02-01 22:11 UTC, closed without merging