Feature/47 класс для отсылки сообщений через телеграм
horba/IntelliGram-D pull request #64
Opened 2018-01-28 13:39 UTC by AkulovBogdan

2018-01-28 20:39 UTC, siriak requested changes

2018-01-28 20:39 UTC, siriak commented on InstaBotPrototype/TelegramTestBot/Telegram/TelegramDb.cs
> +        public async Task<string> GetUsers()
GetUsersAsync
В конце асинхронных методов всегда (кроме обработчиков событий) пишется Async

2018-01-28 20:39 UTC, siriak commented on InstaBotPrototype/TelegramTestBot/Telegram/TelegramDb.cs
> +        public async Task<bool> UserExists(int chatId, SqlConnection connection)
Здесь и далее то же самое

2018-01-28 20:39 UTC, siriak commented on InstaBotPrototype/TelegramTestBot/TelegramTestBot.csproj
> +  <PropertyGroup />
Это что?

2018-01-28 20:39 UTC, siriak commented on InstaBotPrototype/DBMigrator/DBMigrator.csproj
> +    <TargetFrameworkProfile />
Это что?

2018-01-28 20:39 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082226_CreateConfigTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTopic(ConfigID int not null, TopicID int not null)";
Почему ключ убран?

2018-01-28 20:39 UTC, siriak commented on InstaBotPrototype/TelegramTestBot/App.config
> +    <add name="TestDB" connectionString="Data Source=.;Initial Catalog=ISD;Integrated Security=True;Pooling=False" providerName="System.Data.SqlClient" />
Ну, пробел можно и убрать)

2018-01-28 20:42 UTC, AkulovBogdan commented on InstaBotPrototype/TelegramTestBot/Telegram/TelegramDb.cs
> +        public async Task<string> GetUsers()
Тут согласен, исправлю

2018-01-28 20:44 UTC, AkulovBogdan commented on InstaBotPrototype/TelegramTestBot/App.config
> +    <add name="TestDB" connectionString="Data Source=.;Initial Catalog=ISD;Integrated Security=True;Pooling=False" providerName="System.Data.SqlClient" />
))

2018-01-28 20:45 UTC, AkulovBogdan commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082226_CreateConfigTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTopic(ConfigID int not null, TopicID int not null)";
Там должны повторяться ключи, а с одним ключом такое сделать не могу

2018-01-28 20:46 UTC, AkulovBogdan commented on InstaBotPrototype/DBMigrator/DBMigrator.csproj
> +    <TargetFrameworkProfile />
Это из-за того, что все проекты на разных .Net

2018-01-28 20:51 UTC, siriak commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082226_CreateConfigTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTopic(ConfigID int not null, TopicID int not null)";
Может тогда сделать ключом пару Конфиг-Топик? А можно и не делать. На твой выбор.

2018-01-28 20:52 UTC, AkulovBogdan commented on InstaBotPrototype/DBMigrator/Migrations/M2018001082226_CreateConfigTopicTable.cs
> +            ApplyCommand.CommandText = "create table dbo.ConfigTopic(ConfigID int not null, TopicID int not null)";
Хорошо, сделаю

2018-01-29 06:04 UTC, siriak approved these changes

2018-01-30 23:34 UTC, demosglok approved these changes

2018-01-30 23:34 UTC, demosglok commented on InstaBotPrototype/DBMigrator/DBMigrator.csproj
> +    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
ой беда

2018-01-30 23:34 UTC, demosglok commented on InstaBotPrototype/DBMigrator/App.config
> +    <add name="TestDB" connectionString="Data Source=.;Initial Catalog=ISD;Integrated Security=True;Pooling=False" providerName="System.Data.SqlClient"/>
и тут как-то не здраво. не коммить хотя бы такие изменения, если уже не вынесены креденшлы базы данных в отдельный конфиг-файл под гит-игнором

2018-01-30 23:34 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/app.config
> +    <add name="TestDB" connectionString="Data Source=.;Initial Catalog=ISD;Integrated Security=True;Pooling=False" providerName="System.Data.SqlClient"/>
тут пусть будет, да

2018-01-30 23:35 UTC, merged