feature/71 Worker
horba/IntelliGram-D pull request #80
Opened 2018-02-10 13:09 UTC by siriak

2018-02-13 14:35 UTC, demosglok submitted a review, later dismissed
местами не идеально, но пусть пока будет так.  улучшение цикла обработки пользователей и сообщений сделаем на след спринте или вообще ивент-модель будем пилить

2018-02-15 08:46 UTC, groleore requested changes

2018-02-15 08:46 UTC, groleore commented on InstaBotPrototype/Worker/MessageCreator.cs
> +                                var count = command.ExecuteNonQuery();
Не тот метод. Нужно executeScalar. И лучше вынести этот запрос в отдельный метод.

2018-02-15 14:47 UTC, siriak commented
Можно ещё ревьювить

2018-02-17 13:43 UTC, groleore approved these changes

2018-02-19 20:50 UTC, demosglok approved these changes

2018-02-19 20:50 UTC, demosglok commented on InstaBotPrototype/Worker/MessageCreator.cs
> +                        Console.WriteLine("Image # " + counter);
это бы в логгер выводить

2018-02-19 20:50 UTC, demosglok commented on InstaBotPrototype/Worker/MessageCreator.cs
> +                    command.CommandText = "select count(ChatId) from dbo.Messages where ChatId = @chatId and Message = @message";
может ли быть два одинаковых message в одном чате?? если чел одинаковые картинки запостил или разные но распознаватель их одинаково распознал?

2018-02-19 20:51 UTC, merged