Registration and topic configuration bug fixes #3
horba/IntelliGram-D pull request #82
Opened 2018-02-11 10:29 UTC by groleore

2018-02-11 14:27 UTC, siriak requested changes

2018-02-11 14:27 UTC, siriak commented on InstaBotPrototype/InstaBotPrototype/Services/DB/ConfigService.cs
> +                var topicId = GetTagId(current, connection);
Может GetTopicId?

2018-02-13 23:10 UTC, siriak approved these changes

2018-02-19 20:48 UTC, demosglok approved these changes

2018-02-19 20:48 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/DB/ConfigService.cs
> +                var current = tag.Tag.Trim();
я б называл currentTag

2018-02-19 20:48 UTC, demosglok commented on InstaBotPrototype/InstaBotPrototype/Services/DB/ConfigService.cs
> +                var current = topic.Topic.Trim();
а тут currentTopic, для понятности

2018-02-19 20:48 UTC, merged